openapi: 3.0.1
info:
  title: Casa Sea Esta API
  version: 1.0.0
servers:
  - url: https://hostaway-casaseaesta-api.onrender.com

paths:
  /api/guest:
    get:
      summary: Get today's guest info
      parameters:
        - in: query
          name: listingId
          schema:
            type: string
          required: false
          description: Hostaway listing ID (preferred, e.g., 256853)
        - in: query
          name: property
          schema:
            type: string
          required: false
          description: Legacy slug (e.g., casa-sea-esta). Will be mapped to listingId internally.
      responses:
        '200':
          description: Guest found
          content:
            application/json:
              schema:
                type: object
                properties:
                  guestName:
                    type: string
                  checkIn:
                    type: string
                  checkOut:
                    type: string
                  checkInTime:
                    type: string
                  checkOutTime:
                    type: string
                  numberOfGuests:
                    type: string
                  notes:
                    type: string
        '401':
          description: Authentication failed
        '404':
          description: No guest or unauthorized listingId

  /api/vibe-message:
    get:
      summary: Get the current vibe message
      responses:
        '200':
          description: Message retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  guestName:
                    type: string
                  timestamp:
                    type: string
        '404':
          description: No vibe message set

    post:
      summary: Save a new vibe message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                guestName:
                  type: string
      responses:
        '200':
          description: Vibe stored
        '500':
          description: Error saving message
