openapi: 3.0.1
info:
  title: Casa Sea Esta API
  version: 1.0.0
servers:
  - url: https://hostaway-casaseaesta-api.onrender.com
paths:
  /api/guest:
    get:
      summary: Get today's guest info by listing ID
      parameters:
        - in: query
          name: listingId
          required: true
          schema:
            type: string
          description: Hostaway listing ID (e.g., 256853)
      responses:
        '200':
          description: Guest found
          content:
            application/json:
              schema:
                type: object
                properties:
                  guestName:
                    type: string
                  checkIn:
                    type: string
                  checkOut:
                    type: string
                  numberOfGuests:
                    type: string
                  notes:
                    type: string
        '404':
          description: No guest found or unknown listing ID
        '401':
          description: Authentication failed

  /api/vibe-message:
    get:
      summary: Get current vibe message
      responses:
        '200':
          description: Message returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  guestName:
                    type: string
                  timestamp:
                    type: string
        '404':
          description: No vibe set

    post:
      summary: Save a new vibe message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                guestName:
                  type: string
      responses:
        '200':
          description: Vibe stored
        '500':
          description: Error saving
