openapi: 3.0.0
info:
  title: Casa Sea Esta Guest Info
  version: 1.0.0
servers:
  - url: https://hostaway-casaseaesta-api.onrender.com
paths:
  /api/guest:
    get:
      summary: Get today's guest
      operationId: getTodaysGuest
      parameters:
        - name: property
          in: query
          required: true
          schema:
            type: string
          example: casa-sea-esta
      responses:
        '200':
          description: Current guest data
          content:
            application/json:
              schema:
                type: object
                properties:
                  guestName:
                    type: string
                  checkIn:
                    type: string
                    format: date
                  checkInTime:
                    type: string
                  checkOut:
                    type: string
                    format: date
                  checkOutTime:
                    type: string
                  numberOfGuests:
                    type: string
                  notes:
                    type: string
              example:
                guestName: Shelby King
                checkIn: 2025-07-17
                checkInTime: "16"
                checkOut: 2025-07-20
                checkOutTime: "10"
                numberOfGuests: "8"
                notes: ""
